USE STAGING

----EXEC [ETL].[dbo].[RESET_ALL_LOGS] ---- yang ini jangan di-exec karena semua log akan hilang
----EXEC [STAGING].[dbo].[PROC_TRUNCATE_RAW_AJK_PESERTA]

--SELECT TOP 4 * FROM ETL.[dbo].[APPLICATION_EXECUTION_INSTANCE] ORDER BY APPLICATION_EXECUTION_INSTANCE_ID DESC
--SELECT TOP 4 * FROM ETL.[dbo].[TASK_EXECUTION_INSTANCE] ORDER BY TASK_EXECUTION_INSTANCE_ID DESC
SELECT TOP 4 'INITAL' AS ACTION2, * FROM [ind].[CWMPOLDET] WHERE ACTION = 0 ORDER BY CWMPOLDET_ID DESC
SELECT TOP 4 'INSERT' AS ACTION2, * FROM [ind].[CWMPOLDET] WHERE ACTION = 1 ORDER BY CWMPOLDET_ID DESC
SELECT TOP 4 'UPDATE' AS ACTION2, * FROM [ind].[CWMPOLDET] WHERE ACTION = 2 ORDER BY CWMPOLDET_ID DESC
SELECT TOP 4 'DELETE' AS ACTION2, * FROM [ind].[CWMPOLDET] WHERE ACTION = 3 ORDER BY CWMPOLDET_ID DESC
--SELECT TOP 4 ERROR_DESCRIPTION FROM [ETL].[log].[TASK_EXECUTION_ERROR] ORDER BY TASK_ERROR_ID DESC
--SELECT * FROM [ETL].[log].[APPLICATION_EXECUTION_ERROR]
--SELECT * FROM [ETL].[log].[TASK_EXECUTION_VARIABLE_LOG]